"""Initial migration

Revision ID: 81cdf5722fa1
Revises: 
Create Date: 2025-04-09 15:59:13.444543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '81cdf5722fa1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('job_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('churn_trend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('segment_analysis', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('location_analysis', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('future_predictions', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('factor_importance', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('factor_changes', sa.JSON(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('churn_rate',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('high_risk_customers',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('avg_churn_score',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('subscription_length_trends')
        batch_op.drop_column('age_group_trends')
        batch_op.drop_column('total_customers')
        batch_op.drop_column('gender_trends')
        batch_op.drop_column('location_trends')
        batch_op.drop_column('segment_trends')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('customer_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('customer_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('churn_trend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('segment_trends', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('location_trends', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('gender_trends', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('total_customers', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('age_group_trends', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('subscription_length_trends', sqlite.JSON(), nullable=True))
        batch_op.alter_column('avg_churn_score',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('high_risk_customers',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('churn_rate',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('factor_changes')
        batch_op.drop_column('factor_importance')
        batch_op.drop_column('future_predictions')
        batch_op.drop_column('location_analysis')
        batch_op.drop_column('segment_analysis')

    with op.batch_alter_table('batch_job', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('job_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###
